#!/bin/bash
#Initial input checking	
if [ "$1" = "-r" ]; then
	echo Will calculate rows
elif [ "$1" = "-c" ]; then
	echo will calculate columns
else 
	echo "Usage: stats {-rows|-cols} [input_file]"
fi

while read  line
do
	echo "Column 1: $line"

done < test_file
